In [54]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [60]:
df = sns.load_dataset('titanic')
df.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [61]:
X = df[['pclass','age','sibsp']]
y = df['survived']

In [62]:
X.fillna(df['age'].median(),inplace=True)

In [64]:
X.isnull().sum()

pclass    0
age       0
sibsp     0
dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)


In [83]:
# Transformations
# Standardization : fit_transform = Train & transform = Test
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [84]:
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[-1.61413602,  1.25364106, -0.47072241],
       [-0.40055118, -0.47728355, -0.47072241],
       [ 0.81303367,  0.21508629, -0.47072241],
       ...,
       [ 0.81303367,  0.90745614,  1.23056874],
       [-1.61413602, -1.1696534 ,  0.37992316],
       [-1.61413602, -0.63114352, -0.47072241]])

In [85]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 0.81303367, -0.09263364,  0.37992316],
       [-0.40055118,  0.13815631, -0.47072241],
       [ 0.81303367, -0.7080735 , -0.47072241],
       [-0.40055118, -1.78509326, -0.47072241],
       [ 0.81303367, -1.1696534 ,  0.37992316],
       [-1.61413602, -0.24649361, -0.47072241],
       [ 0.81303367, -0.09263364, -0.47072241],
       [ 0.81303367, -1.01579343,  1.23056874],
       [ 0.81303367, -1.01579343, -0.47072241],
       [-1.61413602, -0.78500349, -0.47072241],
       [-1.61413602,  0.59973621,  0.37992316],
       [ 0.81303367,  1.13824609, -0.47072241],
       [ 0.81303367, -0.09263364,  2.08121431],
       [ 0.81303367,  0.06122633, -0.47072241],
       [-0.40055118,  0.52280622, -0.47072241],
       [-1.61413602, -1.01579343, -0.47072241],
       [-1.61413602,  0.98438612,  0.37992316],
       [ 0.81303367, -0.09263364, -0.47072241],
       [-0.40055118, -0.16956362, -0.47072241],
       [-1.61413602,  1.36903603, -0.47072241],
       [ 0.81303367, -0.40035357, -0.470

In [90]:
# we get this modeling datat afetr doing transformation
# Model Building
# fit() for training data & predict for test data
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [91]:
lr.fit(X_train_scaled,y_train)

LogisticRegression()

In [92]:
lr.predict(X_test_scaled)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0], dtype=int64)